### ISSUE TITLE
Potential sortedSkillCount Bug

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#13]
Not the best DNSpy user, so I'll do my best to explain what is happening.

My skill tree mod (https://github.com/korgano/SkillTreeRebuild/releases/tag/v0.2.5 - note: contains an older version of Abilifier.dll) has a persistent issue with abilities disappearing after selecting abilities on lower tiers.

Steps to replicate:
-Install SkillTreeRebuild
-Go to Barracks
-Select MechWarrior with no set abilities/use mod to reset abilities
-Select all options through level 3 of all 4 skill trees, then select ability for Gunnery/Guts/Tactics 4
-Piloting 8 ability options disappear

OR 

-Install SkillTreeRebuild
-Go to Barracks
-Select MechWarrior with no set abilities/use mod to reset abilities
-Select Piloting 4 ability first
-Select Gunnery, Guts, and Tactics 4 abilities
-All other abilities disappear; completing one skill tree first results in all options remaining visible

Not sure what is going on, but I've noticed one major commonality between both situations: in addition to the ability being selected, each tier 4 pip has a trait that affects a stat. 

The Abilifier log doesn't have much to say:

> TRACE: 2022-08-10T16:54:53 - Looping Tactics 5: AbilityDef_ScoutStomp
> TRACE: 2022-08-10T16:54:53 - Add trait AbilityDef_ScoutStomp
> TRACE: 2022-08-10T16:54:53 - abilityToUse: AbilityDef_ScoutStomp
> TRACE: 2022-08-10T16:55:02 - Add primary AbilityDef_ScoutStomp
> TRACE: 2022-08-10T16:55:02 - Looping Tactics 5: AbilityDef_GimpThem
> TRACE: 2022-08-10T16:55:02 - abilityToUse: AbilityDef_ScoutStomp
> TRACE: 2022-08-10T16:55:02 - Looping Tactics 5: TraitDefIndirectReduceTwo
> TRACE: 2022-08-10T16:55:05 - SAFETY FALLBACK Add trait TraitDefIndirectReduceTwo
> TRACE: 2022-08-10T16:55:05 - abilityToUse: AbilityDef_ScoutStomp

I tried to use DNSpy to figure out what was going on, but I am not sure I am looking in the right place. I did discover in Abilifier.Patches that there might be a loop between the following code blocks:
```
bool flag8 = sortedSkillCount.ContainsKey(newAbility.ReqSkill) && sortedSkillCount[newAbility.ReqSkill] < 1 + Mod.modSettings.extraAbilitiesAllowedPerSkill;
								if (flag8)
								{
									__result = true;
								}
								IEnumerable<KeyValuePair<SkillType, int>> source2 = from x in sortedSkillCount
								where x.Value >= 1 + Mod.modSettings.extraAbilitiesAllowedPerSkill
								select x;
```

```
bool flag = !string.IsNullOrEmpty(abilityReq);
```

During the bool flag8, the trait's ID will appear.

It seems like the traits are being counted as part of the sortedSkillCount, but I have no idea if that is actually what's happening, or the error is caused in some other part of the process.

Any and all help would be appreciated.

**Comment by ajkroeg** [comment]
@korgano AbilityDef_Boxer has `"ReqSkillLevel": 10,` but is listed in the array for level 8 in your simgameconstants. that will almost certainly cause problems.

**Comment by korgano** [comment]
Thanks for pointing that out. Fixed it and solved the first issue, but not the second bug.

**Comment by ajkroeg** [comment]
Your AbilityDefs need a cleanup/QAQC pass. For example, AbilityDef_JumpMaven is missing the ReqSkill, ReqSkillLevel, and `"IsPrimaryAbility": true` fields. `AbilityDef_TargetFiring` has the ReqSkill and ReqSkillLevel, but does not have `"IsPrimaryAbility": true`. And so on.

~~Also, you still have a lot of the BTA abilities that you were asked to get rid of. Please do so.~~ nvm, i see the release has been updated
