### ISSUE TITLE
Question about CAC Button

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/Abilifier#14]
XAI is using an older version of CAC and that is all and I have tried everything to disable the target ground button. I have made it useless but it still takes up a spot on the console. My version of CAC cannot disable the button from showing because the setting is unhooked, Can you put in an override in the next version to get rid of it completely?  Also, can you clarify for me what is the best way to add one more displayed icon for pilot skills since CAC is using one of the buttons? I have read your page but for some reason, it isn't clear to me, maybe it is brain fog from the New Year.

**Comment by ajkroeg** [comment]
Abilifier will not be doing anything to directly hide CAC's Attack Ground button. On those ancient versions of CAC, you _might_ be able to just delete the AbilityDef for AttackGround, but I don't recall. If your CAC version is old enough that it isn't creating new ability buttons, you'll want to flip `usingCACabilitySelector` to false. Then Abilifier will handle creating new ability buttons.
