### ISSUE TITLE
Feature Suggestion: patch MechMortarSequence to pull EffectData from Ability_Mortar_[Name]

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#22]
Been experimenting with having Mech Mortars/Thumpers confer Status Effects on targets, and I discovered that even if Status Effects are defined within the EffectData section of a custom Ability_Mortar_[Name] file, they are not applied to targets. Further examination of the MechMortarSequence shows that there's no code that pulls EffectData and applies it to enemies.

Patching the MechMortarSequence to apply EffectData from **only** the Ability_Mortar_[Name] file would allow limited application of debuffs to affected enemies, without the risk of having other abilities stacking on the mortar/thumper attacks, or needing to patch the MechMortarSequence to accept additional valid IDs for bool `isThumper` **and** pull EffectData from WeaponDef.

**Comment by ajkroeg** [comment]
thats fairly outside the scope of what Abilifier does, and anyway CAC already has a much better implementation of artillery and AOE status effects, so i wont be implementing it here. you seem to know what you want for it and where to look, so i suggest implementing your own mod if that functionality is something you want. You can look at AttackSequence.OnAttackSequenceResolveDamage in vanilla code to see how OnHit type effects are applied. Patch MechMortarSequence.AttackNextTarget and pull the EffectData from referenceWeapon.
