### ISSUE TITLE
OnInitializeContract fail due to abilifierId not found (3rd party report)

### ISSUE THREAD

**Issue by korgano** [BattletechModders/Abilifier#25]
A user of my Abilifier based mod seems to be encountering an infinite load issue on campaign maps, but I am not sure I'm interpreting the log correctly.

As far as I know and have experienced, this does not seem to occur in career or single-player skirmish mode.

He's using Abilifier (v1.4.1.4) and a Steam install.

Log attached below:
[Kosis12-BT-log-00.txt](https://github.com/BattletechModders/Abilifier/files/12402738/Kosis12-BT-log-00.txt)

**Comment by ajkroeg** [comment]
theyre missing the AbilifierEffectDataInjector dll
